-- sequences
CREATE SEQUENCE menu_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE order_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE order_item_seq START WITH 1 INCREMENT BY 1;

-- MENU_ITEMS
CREATE TABLE MENU_ITEMS (
  ITEM_ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(200),
  DESCRIPTION VARCHAR2(1000),
  PRICE NUMBER(10,2),
  AVAILABLE NUMBER(1)
);

-- ORDERS
CREATE TABLE ORDERS (
  ORDER_ID NUMBER PRIMARY KEY,
  USERNAME VARCHAR2(100),
  TOTAL_AMOUNT NUMBER(10,2),
  ORDER_DATE TIMESTAMP,
  STATUS VARCHAR2(50)
);

-- ORDER_ITEMS
CREATE TABLE ORDER_ITEMS (
  ID NUMBER PRIMARY KEY,
  ORDER_ID NUMBER,
  ITEM_ID NUMBER,
  QTY NUMBER,
  PRICE NUMBER(10,2),
  CONSTRAINT fk_order_items_order FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
  CONSTRAINT fk_order_items_menu FOREIGN KEY (ITEM_ID) REFERENCES MENU_ITEMS(ITEM_ID)
);

-- sample menu item
INSERT INTO MENU_ITEMS (ITEM_ID, NAME, DESCRIPTION, PRICE, AVAILABLE) VALUES (menu_seq.NEXTVAL, 'Veg Burger', 'Delicious veg burger with special sauce', 99.00, 1);
INSERT INTO MENU_ITEMS (ITEM_ID, NAME, DESCRIPTION, PRICE, AVAILABLE) VALUES (menu_seq.NEXTVAL, 'Paneer Wrap', 'Spicy paneer wrap', 129.00, 1);
COMMIT;
